// Multiple beginner dishes per cook mode so each "추천 받기" can rotate to a
// different recipe instead of always returning the same one.
// Each dish: { ko, en, ing[], koSteps[4], enSteps[4] }.
//   ing = [[korean name, english name, amount(ko)]] — amount scales by servings,
//   and drives both the "정확한 계량" list and the shopping list (owned items removed).
export const DISHES = {
  fridgeClean: [
    { ko: "냉장고 털이 볶음", en: "fridge clean-out stir-fry",
      ing: [["양파","onion","0.5개"],["당근","carrot","0.3개"],["대파","green onion","0.5대"],["간장","soy sauce","1스푼"],["식용유","cooking oil","1스푼"],["참기름","sesame oil","0.5스푼"]],
      koSteps: ["채소는 한입 크기, 두부나 달걀은 부서지지 않게 준비해요.", "중불 팬에 식용유를 두르고 대파를 30초 볶아 향을 내요.", "단단한 재료부터 넣고 간장으로 간을 맞춰요. 김치·고추장이 있으면 짠맛을 보며 줄여요.", "불을 끄고 참기름과 후추를 마지막에 넣어 따뜻하게 담아요."],
      enSteps: ["Cut veg bite-size; keep tofu or egg from breaking.", "Heat oil over medium and stir-fry green onion 30s for aroma.", "Add firm items first and season with soy; reduce salt if kimchi or gochujang is in.", "Off the heat, finish with sesame oil and pepper, plate warm."] },
    { ko: "남은 채소 달걀밥", en: "leftover veggie egg rice",
      ing: [["밥","cooked rice","1공기"],["달걀","egg","1개"],["양파","onion","0.3개"],["간장","soy sauce","1스푼"],["참기름","sesame oil","0.5스푼"],["김","seaweed","0.5장"]],
      koSteps: ["남은 채소를 잘게 썰고 밥을 준비해요.", "팬에 기름을 두르고 채소를 볶아 숨을 죽여요.", "밥을 넣고 간장으로 간한 뒤 달걀을 풀어 빠르게 섞어요.", "참기름과 김을 올려 마무리해요."],
      enSteps: ["Finely chop leftover veg and ready the rice.", "Stir-fry the veg in oil until softened.", "Add rice, season with soy, then scramble in beaten egg.", "Finish with sesame oil and seaweed."] },
    { ko: "두부 채소조림", en: "tofu & veggie braise",
      ing: [["두부","tofu","0.5모"],["양파","onion","0.3개"],["간장","soy sauce","1.5스푼"],["설탕","sugar","0.5스푼"],["대파","green onion","0.3대"],["물","water","50ml"]],
      koSteps: ["두부를 도톰하게 썰고 채소를 준비해요.", "팬에 간장·물·설탕을 넣어 양념을 끓여요.", "두부와 채소를 넣어 약불에서 자작하게 졸여요.", "대파와 깨를 올려 담아요."],
      enSteps: ["Slice tofu thick and prep the veg.", "Simmer a sauce of soy, water and sugar in a pan.", "Add tofu and veg, braise gently until reduced.", "Top with green onion and sesame."] },
    { ko: "한 그릇 채소국", en: "quick veggie soup",
      ing: [["애호박","zucchini","0.3개"],["두부","tofu","0.3모"],["된장","doenjang","1스푼"],["대파","green onion","0.3대"],["마늘","garlic","1톨"],["물","water","400ml"]],
      koSteps: ["채소를 한입 크기로 썰어요.", "물에 된장이나 간장으로 국물 간을 해요.", "단단한 채소부터 넣어 끓이고 두부를 더해요.", "대파를 올려 한소끔 더 끓여 담아요."],
      enSteps: ["Cut vegetables into bite sizes.", "Season water with doenjang or soy.", "Add firm veg first, simmer, then add tofu.", "Add green onion and simmer once more."] },
  ],
  snack: [
    { ko: "치즈 토스트", en: "cheese toast",
      ing: [["식빵","bread","2장"],["치즈","cheese","1장"],["버터","butter","0.5스푼"]],
      koSteps: ["식빵에 버터를 얇게 바르고 치즈를 올려요.", "약불 팬에 올려 한 면당 1~2분 노릇하게 구워요.", "치즈가 녹으면 반으로 접거나 한 장 더 덮어요.", "반으로 잘라 단면이 보이게 담아요."],
      enSteps: ["Spread thin butter on bread and add cheese.", "Toast each side 1-2 min over low heat.", "When the cheese melts, fold or top with another slice.", "Cut in half to show the melty center."] },
    { ko: "감자 치즈전", en: "potato cheese fritter",
      ing: [["감자","potato","1개"],["전분","starch","1스푼"],["치즈","cheese","1장"],["소금","salt","한 꼬집"],["식용유","cooking oil","1스푼"]],
      koSteps: ["감자를 갈거나 잘게 썰어 물기를 빼요.", "소금 약간과 전분을 섞어 동글납작하게 빚어요.", "기름 두른 팬에 양면을 노릇하게 부쳐요.", "치즈를 올려 살짝 녹이고 케첩을 곁들여요."],
      enSteps: ["Grate or finely chop potato and squeeze out water.", "Mix with a little salt and starch; shape into flat rounds.", "Pan-fry both sides golden in oil.", "Top with cheese to melt and serve with ketchup."] },
    { ko: "과일 요거트볼", en: "fruit yogurt bowl",
      ing: [["요거트","yogurt","1컵"],["과일","fruit","0.5컵"],["견과류","nuts","1스푼"],["꿀","honey","1스푼"]],
      koSteps: ["요거트를 그릇에 담아요.", "과일을 한입 크기로 썰어 올려요.", "견과류나 그래놀라를 뿌려요.", "꿀을 살짝 둘러 시원하게 먹어요."],
      enSteps: ["Spoon yogurt into a bowl.", "Top with bite-size fruit.", "Sprinkle nuts or granola.", "Drizzle honey and enjoy chilled."] },
    { ko: "달걀 마요 샌드", en: "egg mayo sandwich",
      ing: [["달걀","egg","2개"],["마요네즈","mayonnaise","1스푼"],["식빵","bread","2장"],["소금","salt","한 꼬집"],["후추","pepper","약간"]],
      koSteps: ["달걀을 완숙으로 삶아 으깨요.", "마요네즈·소금·후추를 넣고 섞어요.", "식빵 사이에 듬뿍 넣어요.", "반으로 잘라 담아요."],
      enSteps: ["Boil eggs firm and mash.", "Mix with mayo, salt and pepper.", "Fill generously between bread.", "Cut in half and serve."] },
  ],
  dessert: [
    { ko: "팬 커스터드", en: "skillet custard",
      ing: [["우유","milk","120ml"],["달걀","egg","1개"],["설탕","sugar","1.5스푼"],["밀가루","flour","2스푼"],["버터","butter","0.5스푼"]],
      koSteps: ["우유·달걀·설탕(+밀가루 약간)을 부드럽게 섞어요.", "버터 녹인 팬에 반죽을 붓고 단 과일을 올려요.", "약불·뚜껑으로 6~8분 익혀 가운데를 살짝 굳혀요.", "가장자리가 노릇하면 설탕을 살짝 뿌려 담아요."],
      enSteps: ["Whisk milk, egg, sugar (+a little flour) until smooth.", "Pour into a buttered pan and add sweet fruit.", "Cook covered on low 6-8 min until the center just sets.", "Dust with sugar when the edges are golden."] },
    { ko: "바나나 팬케이크", en: "banana pancake",
      ing: [["바나나","banana","1개"],["달걀","egg","1개"],["우유","milk","50ml"],["밀가루","flour","4스푼"],["꿀","honey","1스푼"]],
      koSteps: ["바나나를 으깨 달걀·우유·밀가루와 섞어요.", "약불 팬에 한 국자씩 올려요.", "기포가 올라오면 뒤집어 노릇하게 익혀요.", "꿀이나 시럽을 둘러 담아요."],
      enSteps: ["Mash banana and mix with egg, milk and flour.", "Ladle onto a low-heat pan.", "Flip when bubbles appear and cook golden.", "Drizzle honey or syrup."] },
    { ko: "우유 푸딩", en: "milk pudding",
      ing: [["우유","milk","200ml"],["설탕","sugar","2스푼"],["젤라틴","gelatin","5g"]],
      koSteps: ["우유·설탕을 데우고 젤라틴(또는 한천)을 녹여요.", "틀에 부어 식힌 뒤 냉장고에서 굳혀요.", "굳으면 접시에 뒤집어 빼요.", "과일이나 시럽을 곁들여요."],
      enSteps: ["Warm milk and sugar, dissolve gelatin (or agar).", "Pour into molds, cool, then set in the fridge.", "Unmold onto a plate once firm.", "Serve with fruit or syrup."] },
    { ko: "초코 머그케이크", en: "chocolate mug cake",
      ing: [["밀가루","flour","4스푼"],["코코아","cocoa","1스푼"],["설탕","sugar","2스푼"],["우유","milk","3스푼"],["식용유","cooking oil","1스푼"]],
      koSteps: ["머그컵에 밀가루·코코아·설탕·우유를 섞어요.", "기름 한 스푼을 넣어 촉촉하게 해요.", "전자레인지에 1분 30초 돌려요.", "살짝 식혀 초콜릿을 올려 담아요."],
      enSteps: ["In a mug, mix flour, cocoa, sugar and milk.", "Add a spoon of oil for moisture.", "Microwave about 1 min 30 sec.", "Cool slightly and top with chocolate."] },
  ],
  bread: [
    { ko: "우유 팬브레드", en: "milk pan bread",
      ing: [["밀가루","flour","0.75컵"],["우유","milk","80ml"],["설탕","sugar","1스푼"],["소금","salt","한 꼬집"],["버터","butter","1스푼"]],
      koSteps: ["밀가루·우유·설탕·소금을 볼에 넣고 되직하게 섞어요.", "버터를 녹여 반죽에 섞고 3분 쉬게 해요. 묽으면 밀가루를 조금 더 넣어요.", "약불 팬에 1.5cm 두께로 펴고 뚜껑을 덮어 5~6분, 뒤집어 4분 더 익혀요.", "겉이 노릇하면 버터를 살짝 올려 윤기 있게 담아요."],
      enSteps: ["Mix flour, milk, sugar and salt into a thick batter.", "Melt butter, fold it in, rest 3 min; add a little flour if loose.", "Spread 1.5cm thick in a low-heat pan, cover 5-6 min, flip 4 more.", "When golden, brush with butter for a glossy finish."] },
    { ko: "치즈 갈릭 브레드", en: "cheese garlic bread",
      ing: [["식빵","bread","2장"],["마늘","garlic","2톨"],["버터","butter","1스푼"],["치즈","cheese","1장"],["파슬리","parsley","약간"]],
      koSteps: ["식빵이나 빵에 다진 마늘과 녹인 버터를 발라요.", "치즈를 올리고 약불 팬이나 에어프라이어에 넣어요.", "치즈가 녹고 겉이 바삭해질 때까지 5~7분 구워요.", "파슬리를 뿌려 따뜻할 때 잘라 담아요."],
      enSteps: ["Spread minced garlic and melted butter on bread.", "Top with cheese and place in a low-heat pan or air fryer.", "Bake 5-7 min until the cheese melts and the top is crisp.", "Sprinkle parsley and slice while warm."] },
    { ko: "단호박 모닝롤", en: "sweet pumpkin rolls",
      ing: [["단호박","sweet pumpkin","0.5개"],["밀가루","flour","0.5컵"],["우유","milk","50ml"],["설탕","sugar","1스푼"],["버터","butter","0.5스푼"]],
      koSteps: ["삶아 으깬 단호박에 밀가루·우유·설탕을 섞어 부드러운 반죽을 만들어요.", "작게 동글려 팬에 올리고 뚜껑을 덮어요.", "약불에서 양면을 노릇하게 7~8분 익혀요.", "속이 폭신하면 꿀이나 버터를 곁들여 담아요."],
      enSteps: ["Mash steamed pumpkin and mix with flour, milk and sugar into a soft dough.", "Shape into small rounds and place in a covered pan.", "Cook over low heat 7-8 min until both sides are golden.", "When fluffy inside, serve with honey or butter."] },
    { ko: "통밀 팬케이크 브레드", en: "whole-wheat pancake bread",
      ing: [["통밀가루","whole-wheat flour","0.75컵"],["우유","milk","80ml"],["달걀","egg","1개"],["설탕","sugar","1스푼"],["베이킹파우더","baking powder","한 꼬집"]],
      koSteps: ["통밀가루(또는 밀가루)·우유·달걀·설탕을 멍울 없이 섞어요.", "베이킹파우더가 있으면 한 꼬집 넣어 더 폭신하게 해요.", "약불 팬에 한 국자씩 올리고 기포가 올라오면 뒤집어요.", "노릇하게 구워 시럽이나 잼을 곁들여요."],
      enSteps: ["Whisk whole-wheat (or plain) flour, milk, egg and sugar until smooth.", "Add a pinch of baking powder if you have it for fluffiness.", "Ladle onto a low-heat pan; flip when bubbles appear.", "Cook golden and serve with syrup or jam."] },
    { ko: "옥수수 콘브레드", en: "corn bread",
      ing: [["밀가루","flour","0.5컵"],["옥수수","corn","0.5컵"],["우유","milk","60ml"],["설탕","sugar","1스푼"],["소금","salt","한 꼬집"],["버터","butter","0.5스푼"]],
      koSteps: ["밀가루·옥수수·우유·설탕·소금을 섞어 반죽해요.", "버터를 조금 넣어 부드럽게 만들어요.", "약불 팬에 펴고 뚜껑을 덮어 양면을 천천히 익혀요.", "노릇하면 버터를 올려 담아요."],
      enSteps: ["Mix flour, corn, milk, sugar and salt into a batter.", "Add a little butter to soften.", "Spread in a low-heat pan, cover, cook both sides slowly.", "Top with butter when golden."] },
  ],
  party: [
    { ko: "한입 카나페", en: "bite canapes",
      ing: [["크래커","cracker","6개"],["치즈","cheese","1장"],["햄","ham","2장"],["과일","fruit","0.3컵"]],
      koSteps: ["크래커나 바게트를 한입 크기로 준비해요.", "치즈·햄·과일을 작게 올려요.", "마요나 잼으로 포인트를 줘요.", "색이 번갈아 보이게 접시에 담아요."],
      enSteps: ["Prep crackers or baguette in bite sizes.", "Top with small cheese, ham and fruit.", "Add mayo or jam accents.", "Arrange with alternating colors."] },
    { ko: "새우 감자 그라탕", en: "shrimp potato gratin",
      ing: [["감자","potato","1개"],["새우","shrimp","5마리"],["우유","milk","80ml"],["치즈","cheese","1장"],["후추","pepper","약간"]],
      koSteps: ["감자를 삶아 으깨고 새우는 데쳐요.", "우유·치즈와 섞어 그릇에 담아요.", "치즈를 올려 오븐이나 에어프라이어에 구워요.", "노릇해지면 후추를 뿌려 담아요."],
      enSteps: ["Boil and mash potato; blanch shrimp.", "Mix with milk and cheese in a dish.", "Top with cheese and bake in oven or air fryer.", "Finish with pepper when golden."] },
    { ko: "치즈 플래터", en: "cheese platter",
      ing: [["치즈","cheese","100g"],["견과류","nuts","2스푼"],["건과일","dried fruit","2스푼"],["크래커","cracker","5개"],["꿀","honey","1스푼"]],
      koSteps: ["여러 치즈를 한입 크기로 썰어요.", "견과류와 말린 과일을 곁들여요.", "크래커와 꿀을 함께 놓아요.", "높낮이를 주어 풍성하게 담아요."],
      enSteps: ["Slice assorted cheeses into bites.", "Add nuts and dried fruit.", "Place crackers and honey alongside.", "Arrange with height for abundance."] },
    { ko: "닭봉 오븐구이", en: "oven-roast chicken wings",
      ing: [["닭봉","chicken wingette","6개"],["소금","salt","한 꼬집"],["후추","pepper","약간"],["간장","soy sauce","1스푼"],["식용유","cooking oil","0.5스푼"]],
      koSteps: ["닭봉에 소금·후추·간장으로 밑간해요.", "기름을 살짝 발라 팬이나 에어프라이어에 넣어요.", "180도에서 양면을 노릇하게 구워요.", "소스를 발라 한 번 더 구워 윤기를 내요."],
      enSteps: ["Season chicken wingettes with salt, pepper and soy.", "Brush oil and place in a pan or air fryer.", "Roast at 180C until both sides are golden.", "Glaze with sauce and roast once more for shine."] },
  ],
  korean: [
    { ko: "김치볶음밥", en: "kimchi fried rice",
      ing: [["김치","kimchi","0.7컵"],["밥","cooked rice","1공기"],["간장","soy sauce","1스푼"],["고춧가루","gochugaru","0.5스푼"],["참기름","sesame oil","0.5스푼"],["달걀","egg","1개"]],
      koSteps: ["김치를 잘게 썰고 밥을 준비해요.", "팬에 기름을 두르고 김치를 볶아 신맛을 부드럽게 해요.", "밥을 넣고 간장·고춧가루로 간을 맞춰 볶아요.", "참기름을 두르고 달걀프라이를 올려요."],
      enSteps: ["Chop kimchi and ready the rice.", "Stir-fry kimchi in oil to soften the tang.", "Add rice and season with soy and gochugaru.", "Finish with sesame oil and a fried egg."] },
    { ko: "된장찌개", en: "doenjang stew",
      ing: [["된장","doenjang","1스푼"],["두부","tofu","0.5모"],["애호박","zucchini","0.3개"],["양파","onion","0.3개"],["대파","green onion","0.3대"],["물","water","400ml"]],
      koSteps: ["물에 된장을 풀고 멸치나 다시마로 육수를 내요.", "두부·애호박·양파를 한입 크기로 넣어요.", "끓으면 고춧가루와 마늘로 맛을 더해요.", "대파를 올려 한소끔 더 끓여요."],
      enSteps: ["Dissolve doenjang in water with anchovy or kelp stock.", "Add bite-size tofu, zucchini and onion.", "When boiling, add gochugaru and garlic.", "Top with green onion and simmer once more."] },
    { ko: "제육볶음", en: "spicy pork stir-fry",
      ing: [["돼지고기","pork","200g"],["고추장","gochujang","1스푼"],["간장","soy sauce","1스푼"],["설탕","sugar","0.5스푼"],["양파","onion","0.5개"],["마늘","garlic","2톨"]],
      koSteps: ["돼지고기에 고추장·간장·설탕·마늘로 양념해요.", "센 불 팬에 양파와 함께 볶아요.", "고기가 익으면 대파를 넣어요.", "참기름을 둘러 마무리해요."],
      enSteps: ["Marinate pork with gochujang, soy, sugar and garlic.", "Stir-fry with onion over high heat.", "Add green onion once the pork is cooked.", "Finish with sesame oil."] },
    { ko: "계란말이", en: "rolled omelette",
      ing: [["달걀","egg","3개"],["소금","salt","한 꼬집"],["당근","carrot","0.2개"],["대파","green onion","0.2대"],["식용유","cooking oil","0.5스푼"]],
      koSteps: ["달걀을 풀고 소금과 잘게 썬 채소를 넣어요.", "약불 팬에 얇게 부어 살짝 익으면 말아요.", "빈 자리에 다시 부어 겹겹이 말아요.", "한 김 식혀 먹기 좋게 썰어요."],
      enSteps: ["Beat eggs with salt and finely chopped veg.", "Pour thin on a low-heat pan and roll as it sets.", "Add more egg and keep rolling in layers.", "Cool briefly and slice."] },
  ],
  japanese: [
    { ko: "오야코동", en: "oyakodon",
      ing: [["닭고기","chicken","150g"],["양파","onion","0.5개"],["달걀","egg","2개"],["간장","soy sauce","1스푼"],["설탕","sugar","0.5스푼"],["밥","cooked rice","1공기"]],
      koSteps: ["양파를 채 썰고 닭고기를 한입 크기로 준비해요.", "간장·설탕·물로 소스를 만들어 끓여요.", "닭과 양파를 익히고 달걀을 풀어 부드럽게 덮어요.", "밥 위에 올리고 김을 뿌려요."],
      enSteps: ["Slice onion and cut chicken into bites.", "Simmer a sauce of soy, sugar and water.", "Cook chicken and onion, then pour beaten egg to set softly.", "Spoon over rice and add seaweed."] },
    { ko: "연어 데리야끼", en: "salmon teriyaki",
      ing: [["연어","salmon","150g"],["간장","soy sauce","1스푼"],["설탕","sugar","0.5스푼"],["맛술","cooking wine","0.5스푼"],["소금","salt","한 꼬집"]],
      koSteps: ["연어에 소금을 살짝 뿌려 물기를 닦아요.", "팬에 구워 노릇하게 익혀요.", "간장·설탕·맛술 소스를 넣어 졸여요.", "소스를 끼얹어 밥과 함께 담아요."],
      enSteps: ["Lightly salt salmon and pat dry.", "Pan-sear until golden.", "Add a soy-sugar-mirin sauce and reduce.", "Glaze and serve with rice."] },
    { ko: "우동", en: "udon",
      ing: [["우동면","udon noodle","1봉지"],["다시마","kelp","1장"],["간장","soy sauce","1스푼"],["대파","green onion","0.3대"],["어묵","fish cake","1장"]],
      koSteps: ["다시마·간장으로 국물을 내요.", "우동면을 데쳐 그릇에 담아요.", "국물을 붓고 대파·어묵을 올려요.", "고춧가루나 김을 더해 따뜻하게 먹어요."],
      enSteps: ["Make broth with kelp and soy.", "Blanch udon and place in a bowl.", "Pour broth and top with green onion and fish cake.", "Add chili or seaweed and serve hot."] },
    { ko: "일본식 카레", en: "Japanese curry",
      ing: [["양파","onion","0.5개"],["당근","carrot","0.3개"],["감자","potato","1개"],["카레","curry","2스푼"],["밥","cooked rice","1공기"]],
      koSteps: ["양파·당근·감자를 깍둑 썰어 볶아요.", "물을 붓고 재료가 익을 때까지 끓여요.", "카레를 풀어 농도가 날 때까지 저어요.", "밥 위에 부어 담아요."],
      enSteps: ["Cube and saute onion, carrot and potato.", "Add water and simmer until tender.", "Stir in curry and cook until thick.", "Pour over rice."] },
  ],
  chinese: [
    { ko: "새우볶음밥", en: "shrimp fried rice",
      ing: [["새우","shrimp","5마리"],["달걀","egg","1개"],["밥","cooked rice","1공기"],["대파","green onion","0.5대"],["간장","soy sauce","1스푼"],["굴소스","oyster sauce","0.7스푼"]],
      koSteps: ["새우·달걀·대파를 준비해요.", "센 불 팬에 달걀을 먼저 볶아 덜어둬요.", "밥과 새우를 볶고 간장·굴소스로 간해요.", "달걀과 대파를 넣어 빠르게 마무리해요."],
      enSteps: ["Ready shrimp, egg and green onion.", "Scramble egg first over high heat and set aside.", "Stir-fry rice and shrimp; season with soy and oyster sauce.", "Return egg and onion and finish fast."] },
    { ko: "마파두부", en: "mapo tofu",
      ing: [["두부","tofu","0.7모"],["다진 고기","ground meat","80g"],["두반장","doubanjiang","1스푼"],["마늘","garlic","1톨"],["간장","soy sauce","0.5스푼"],["전분","starch","0.5스푼"],["대파","green onion","0.3대"]],
      koSteps: ["두부를 깍둑 썰고 다진 고기를 준비해요.", "두반장·마늘을 볶아 향을 내요.", "물과 간장을 넣고 두부를 넣어 끓여요.", "전분물로 농도를 내고 대파를 올려요."],
      enSteps: ["Cube tofu and ready ground meat.", "Saute doubanjiang and garlic for aroma.", "Add water and soy, then tofu, and simmer.", "Thicken with starch slurry and top with onion."] },
    { ko: "탕수육풍 볶음", en: "sweet & sour pork",
      ing: [["돼지고기","pork","200g"],["전분","starch","3스푼"],["식초","vinegar","1스푼"],["설탕","sugar","1.5스푼"],["간장","soy sauce","1스푼"],["케첩","ketchup","1스푼"],["파인애플","pineapple","0.3컵"]],
      koSteps: ["고기에 전분을 묻혀 바삭하게 구워요.", "식초·설탕·간장·케첩으로 소스를 끓여요.", "파인애플이나 채소를 넣어요.", "소스에 고기를 버무려 담아요."],
      enSteps: ["Coat pork in starch and fry crisp.", "Boil a sauce of vinegar, sugar, soy and ketchup.", "Add pineapple or vegetables.", "Toss the pork in the sauce."] },
    { ko: "가지볶음", en: "stir-fried eggplant",
      ing: [["가지","eggplant","1개"],["마늘","garlic","1톨"],["간장","soy sauce","1스푼"],["굴소스","oyster sauce","0.5스푼"],["대파","green onion","0.3대"],["식용유","cooking oil","1스푼"]],
      koSteps: ["가지를 길게 썰어 소금에 살짝 절여요.", "기름에 마늘을 볶아 향을 내요.", "가지를 넣고 간장·굴소스로 볶아요.", "대파를 올려 마무리해요."],
      enSteps: ["Cut eggplant into strips and lightly salt.", "Saute garlic in oil for aroma.", "Add eggplant and stir-fry with soy and oyster sauce.", "Finish with green onion."] },
  ],
  meat: [
    { ko: "삼겹살구이", en: "grilled pork belly",
      ing: [["삼겹살","pork belly","200g"],["소금","salt","한 꼬집"],["후추","pepper","약간"],["쌈채소","ssam greens","1줌"],["김치","kimchi","0.3컵"]],
      koSteps: ["삼겹살을 키친타월로 물기를 닦아요.", "달군 팬에 펼쳐 한 면을 노릇하게 구워요.", "뒤집어 익히고 소금·후추로 간해요.", "쌈채소나 김치와 함께 담아요."],
      enSteps: ["Pat pork belly dry.", "Sear one side golden in a hot pan.", "Flip to cook through; season with salt and pepper.", "Serve with ssam greens or kimchi."] },
    { ko: "스테이크", en: "pan steak",
      ing: [["소고기","beef","200g"],["소금","salt","한 꼬집"],["후추","pepper","약간"],["버터","butter","1스푼"],["마늘","garlic","2톨"]],
      koSteps: ["고기를 실온에 두고 소금·후추로 밑간해요.", "센 불 팬에 양면을 강하게 구워 색을 내요.", "버터·마늘을 넣어 향을 입혀요.", "5분 레스팅 후 썰어 담아요."],
      enSteps: ["Rest meat to room temp; season with salt and pepper.", "Sear both sides hard for color.", "Add butter and garlic to baste.", "Rest 5 min, then slice."] },
    { ko: "닭다리 간장조림", en: "soy-braised chicken",
      ing: [["닭다리","chicken leg","2개"],["간장","soy sauce","2스푼"],["설탕","sugar","1스푼"],["마늘","garlic","2톨"],["물","water","100ml"],["대파","green onion","0.3대"]],
      koSteps: ["닭다리에 칼집을 내요.", "간장·설탕·마늘·물로 양념을 만들어요.", "팬에 닭과 양념을 넣고 졸여요.", "윤기 나면 대파를 올려 담아요."],
      enSteps: ["Score the chicken thighs.", "Make a sauce of soy, sugar, garlic and water.", "Braise chicken in the sauce until reduced.", "Top with green onion when glossy."] },
    { ko: "양념불고기", en: "marinated bulgogi",
      ing: [["소고기","beef","200g"],["간장","soy sauce","2스푼"],["설탕","sugar","1스푼"],["마늘","garlic","2톨"],["참기름","sesame oil","0.5스푼"],["양파","onion","0.5개"]],
      koSteps: ["얇은 소고기에 간장·설탕·마늘·참기름 양념을 해요.", "양파와 함께 30분 재워요.", "센 불 팬에 빠르게 볶아요.", "국물이 자작해지면 깨를 뿌려 담아요."],
      enSteps: ["Marinate thin beef in soy, sugar, garlic and sesame oil.", "Rest with onion for 30 min.", "Stir-fry quickly over high heat.", "Sprinkle sesame as the sauce reduces."] },
  ],
  quick: [
    { ko: "간장계란밥", en: "soy egg rice",
      ing: [["밥","cooked rice","1공기"],["달걀","egg","1개"],["간장","soy sauce","1스푼"],["참기름","sesame oil","0.5스푼"],["김","seaweed","0.5장"]],
      koSteps: ["따뜻한 밥을 그릇에 담아요.", "달걀프라이를 반숙으로 올려요.", "간장과 참기름을 살짝 둘러요.", "김을 부숴 올려 비벼 먹어요."],
      enSteps: ["Put warm rice in a bowl.", "Top with a runny fried egg.", "Drizzle soy sauce and sesame oil.", "Crumble seaweed and mix."] },
    { ko: "참치마요덮밥", en: "tuna mayo bowl",
      ing: [["참치캔","canned tuna","0.5캔"],["마요네즈","mayonnaise","1스푼"],["밥","cooked rice","1공기"],["간장","soy sauce","0.5스푼"],["김","seaweed","약간"]],
      koSteps: ["참치캔의 기름을 빼요.", "마요네즈와 섞어요.", "밥 위에 올리고 간장을 살짝 둘러요.", "김가루나 대파를 뿌려요."],
      enSteps: ["Drain canned tuna.", "Mix with mayonnaise.", "Spoon over rice and add a little soy.", "Sprinkle seaweed flakes or green onion."] },
    { ko: "라면 업그레이드", en: "upgraded ramen",
      ing: [["라면","instant noodle","1봉지"],["달걀","egg","1개"],["대파","green onion","0.3대"],["치즈","cheese","1장"]],
      koSteps: ["라면을 봉지 표시대로 끓여요.", "달걀과 대파를 넣어요.", "치즈나 김치를 더해 맛을 살려요.", "불을 끄고 그릇에 담아요."],
      enSteps: ["Cook ramen per the package.", "Add egg and green onion.", "Boost with cheese or kimchi.", "Turn off heat and serve."] },
    { ko: "어묵우동탕", en: "fish cake udon soup",
      ing: [["어묵","fish cake","2장"],["간장","soy sauce","1스푼"],["다시마","kelp","1장"],["대파","green onion","0.3대"],["우동면","udon noodle","1봉지"]],
      koSteps: ["물에 간장·다시마로 국물을 내요.", "어묵과 대파를 넣어 끓여요.", "면이나 밥을 곁들여요.", "후추를 살짝 뿌려 따뜻하게 먹어요."],
      enSteps: ["Make broth with soy and kelp.", "Add fish cake and green onion.", "Serve with noodles or rice.", "Finish with a little pepper."] },
  ],
};
